// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TandooriRecipe.Models;

namespace TandooriRecipe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191209004303_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TandooriRecipe.Models.Favourite", b =>
                {
                    b.Property<int>("FavouriteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipeId");

                    b.Property<string>("UserName");

                    b.Property<string>("recipeName");

                    b.HasKey("FavouriteID");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Ingredients", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ingredient");

                    b.Property<int>("RecipeId");

                    b.Property<int?>("RecipeViewModelId");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipeViewModelId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<string>("Directions");

                    b.Property<string>("Name");

                    b.Property<int>("RecipeViewModelId");

                    b.HasKey("RecipeId");

                    b.HasIndex("RecipeViewModelId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Reviews", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipeId");

                    b.Property<int>("RecipeViewModelId");

                    b.Property<string>("ReviewDesc");

                    b.HasKey("ReviewId");

                    b.HasIndex("RecipeViewModelId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TandooriRecipe.Models.ViewsModel.RecipeViewModel", b =>
                {
                    b.Property<int>("RecipeViewModelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("RecipeViewModelId");

                    b.ToTable("RecipesVM");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Ingredients", b =>
                {
                    b.HasOne("TandooriRecipe.Models.ViewsModel.RecipeViewModel")
                        .WithMany("IngredientsItem")
                        .HasForeignKey("RecipeViewModelId");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Recipe", b =>
                {
                    b.HasOne("TandooriRecipe.Models.ViewsModel.RecipeViewModel")
                        .WithOne("recipeItem")
                        .HasForeignKey("TandooriRecipe.Models.Recipe", "RecipeViewModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TandooriRecipe.Models.Reviews", b =>
                {
                    b.HasOne("TandooriRecipe.Models.ViewsModel.RecipeViewModel")
                        .WithMany("ReviewsItem")
                        .HasForeignKey("RecipeViewModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
