// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TandooriRecipe.Models;

namespace TandooriRecipe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191125165131_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TandooriRecipe.Models.RecipeModel", b =>
                {
                    b.Property<string>("RecipeModelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<string>("Directions");

                    b.Property<string>("Ingredients");

                    b.Property<string>("Name");

                    b.Property<int>("RecipeId");

                    b.Property<int>("TimeRequired");

                    b.HasKey("RecipeModelID");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
