// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TandooriRecipe.Models;

namespace TandooriRecipe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TandooriRecipe.Models.Ingredient", b =>
                {
                    b.Property<string>("IngredientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<string>("RecipeModelID");

                    b.HasKey("IngredientID");

                    b.HasIndex("RecipeModelID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("TandooriRecipe.Models.RecipeModel", b =>
                {
                    b.Property<string>("RecipeModelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Desciption");

                    b.Property<string>("Directions");

                    b.Property<string>("Name");

                    b.Property<int>("RecipeId");

                    b.Property<int>("TimeRequired");

                    b.HasKey("RecipeModelID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("TandooriRecipe.Models.Ingredient", b =>
                {
                    b.HasOne("TandooriRecipe.Models.RecipeModel")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeModelID");
                });
#pragma warning restore 612, 618
        }
    }
}
